# Use BuildKit-aware FROM line
FROM --platform=$BUILDPLATFORM node:20-alpine3.19

# Install packages
RUN apk add --no-cache g++ make py3-pip supervisor bash caddy dos2unix

# Install tools
RUN npm install -g pnpm@10.6.1 pm2

WORKDIR /app

# Copy source
COPY . /app

# Copy configs
COPY var/docker/supervisord.conf /etc/supervisord.conf
COPY var/docker/Caddyfile /app/Caddyfile
COPY var/docker/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY var/docker/supervisord/caddy.conf /etc/supervisor.d/caddy.conf

# Fix line endings and permissions
RUN dos2unix /usr/local/bin/docker-entrypoint.sh && chmod +x /usr/local/bin/docker-entrypoint.sh

RUN pnpm install
RUN pnpm run build

EXPOSE 4200 3000 80

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
